### ISSUE TITLE
Folder for Extension methods

### ISSUE THREAD

**Issue by DishanH** [jasontaylordev/CleanArchitecture#108]
**Is your feature request related to a problem? Please describe.**
I couldn't find a proper place to put extension methods that are shared among different features. We do have a lot of extension methods like IEnumerableExtension, IQueryableExtension, DateTimeOffSetExtension, etc.  

**Describe the solution you'd like**
Can we have a separate folder inside Application > Common > **Extensions or Helpers**

**Describe alternatives you've considered**
1. Create a subfolder inside the application layer and added the related extension to that folder. 
2. Create s subfolder inside the domain layer and share extensions among different applications.

**Comment by MCCshreyas** [comment]
Extensions methods should be in Application layer and not should be the part of Domain layer.
Because extension methods you are going to use in your commands and queries to format the result. 
The best place to go extension methods is Application - > Common - > ExtensionMethods. 

Why common folder? Because the things are in common are the things that are shared across the application layer. Just like Models folder in common you can have ExtensionMethods folder.

**Comment by DishanH** [comment]
@MCCshreyas Thanks for the information. 
IEnumarableExtenctions for data shaping with ExpandoObject
`public static IEnumerable<ExpandoObject> ShapeData<TSource>(this IEnumerable<TSource> source, string fields)`

**Comment by MCCshreyas** [comment]
First a fall, I didn't get why to used ExpandoObject if you know the exact type as you are implementing Queries and Commands for the same. 
But still, if you would like to, rather than having extension methods for mapping, you can use AutoMapper itself to map from `yourType` to `ExpandoObject`. 
You just need to create the mapping for the same. 
You can refer following link on how to do it. 

Automapper doc - https://docs.automapper.org/en/stable/Dynamic-and-ExpandoObject-Mapping.html

Stackoverflow thread - https://stackoverflow.com/questions/7778216/allow-mapping-of-dynamic-types-using-automapper-or-similar

**Comment by DishanH** [comment]
@MCCshreyas Thanks. I didn't know AutoMapper supports dynamic dictionary mapping.i'll try that.
by the way, I'm thinking of passing todo item collection to todo list create action. To create todo items in one goal. how can I achieve this kind of thing without duplicating validations?

**Comment by MCCshreyas** [comment]
The template shows off simple scenario, but you can extend as much as per the need and requirement,
