### ISSUE TITLE
UnhandledExceptionBehaviour still catches exceptions handled by ApiExceptionFilter

### ISSUE THREAD

**Issue by AlQuraian** [jasontaylordev/CleanArchitecture#117]
When I throw an exception within Mediatr flow I still see the error "Unhandled Exception" being returned. Even if the exception is declared in the handlers within ApiExceptionFilter.

**Comment by jasontaylordev** [comment]
Hi @AlQuraian - thanks for raising. Please provide more details regarding the expected vs. actual results. Currently, any exceptions within the application layer will be logged. It is expected that the client will handle these exceptions. In the case of a known exception, the ApiExceptionFilter will intercept and return a problem details object instead.

**Comment by AlQuraian** [comment]
Hi @jasontaylordev - Thanks for your reply and work.
Maybe I misunderstood the expected behavior. I thought that if an application exception such as NotFoundException is thrown and is handled by the ApiExceptionFilter, then it should not be caught/logged by UnhandledExceptionBehaviour, as it says "unhandled" when it's clearly handled by the filter.
Is this the expected behavior?

**Comment by jasontaylordev** [comment]
No worries @AlQuraian and thanks for getting back to me. 

> Is this the expected behavior?

Yes. In the context of the Application layer, it is an unhandled exception in that there is no handler in the Application layer designed to deal with this exception. It is therefore logged, within the Application layer, as an unhandled exception.

However, in the context of the client, it is a handled exception - since I've implemented an ApiException filter.

Please recall that Core (Application + Domain) is independent of Presentation. So, the fact that the exception is handled within Presentation has no relevance to Core.

I've considered an alternative approach. Within Application, perhaps only non-custom exceptions should be logged. This would exclude custom Application exceptions such as NotFound. Strategies to implement this feature could include 1) a custom base class for all custom exceptions, 2) checking exception namespace to see if it is included in the current solution. But both approaches increase the complexity, which is something I would like to avoid.

I try to keep this template simple since it is then easier to understand and it is easier to extend.

So for your approach, you might like to consider an alternative approach and filter out those custom exceptions. What are your thoughts?

**Comment by AlQuraian** [comment]
Now it's clear to me. Thanks for the elaborate answer.
I agree with you to keep it simple as it is.

Maybe there should be a comment in the UnhandledExceptionBehaviour to clarify that exceptions will be logged even if handled by the client layer, to avoid anyone getting confused and maybe creating an issue here.

Thanks again and keep up the great work!
