### ISSUE TITLE
Missing WebUI.IntegrationTests project 

### ISSUE THREAD

**Issue by Alexei000** [jasontaylordev/CleanArchitecture#124]
**Is your feature request related to a problem? Please describe.**
This is not a feature request, just asking to clarify a missing project. The [GOTO 2019](https://www.youtube.com/watch?v=dK4Yb6-LxAk&feature=youtu.be#t=47m58s) presentation of this solution also includes a WebUI.IntegrationTests projects that seems to be missing here. 

**Describe the solution you'd like**
Find out what happened to the missing project.

**Describe alternatives you've considered**
None

**Additional context**
None.

Thank you.

**Comment by jasontaylordev** [comment]
Hi @Alexei000. Thanks for your interest.

I've upgraded the approach to testing since then, please check out this talk; https://www.youtube.com/watch?v=2UJ7mAtFuio.

The old project included ASP.NET Core Integration Tests, you can view it here: https://github.com/jasontaylordev/CleanArchitecture/tree/de836ab45bc125bafffde0ffcc169e5cfea2b7f6/tests.

The new project focuses on subcutaneous tests at the application layer. The old project focuses on integration tests at the API layer. They were both testing the same thing, the new approach is much simpler and cleaner.

Let me know if you have any questions. 😊
