### ISSUE TITLE
Feature Request: React Presentation Layer

### ISSUE THREAD

**Issue by hbermani** [jasontaylordev/CleanArchitecture#13]
Thank you Jason and the community for the brilliant work on this solution. I just finished watching your latest NDC talk and I think it's brilliant. 

I was wondering whether anyone is forking this to make a version with React as the front-end? I will try and give it a go but I am really new to it.

H.

**Comment by eloekset** [comment]
I also just recently saw the [NDC Sydney 2019 talk](https://youtu.be/5OtUm1BLmG0). Since it’s mentioned, we should link to it.

**Comment by JasonGT** [comment]
> Thank you Jason and the community for the brilliant work on this solution. I just finished watching your latest NDC talk and I think it's brilliant.

Thanks so much, really appreciate the feedback. 😄

> I was wondering whether anyone is forking this to make a version with React as the front-end? I will try and give it a go but I am really new to it.

This is something that I'd really like to see happen next year. In fact, it would be great to have front ends for Angular, React, Vue (my favourite), and Blazor.

If you want to learn more, take a look here - https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-3.1&tabs=visual-studio. Essentially, there are two React templates - React and React with Redux. The React template is most suited, since it supports authentication with ASP.NET Core Identity + IdentityServer out of the box.

**Comment by hbermani** [comment]
I think i just about got React to work with it, but didn't implement the Todo app logic. Currently battling with integrating Azure AD sign in with Identity Server in the template. Failing at it but will grind it until I succeed XD!!
I have so much to learn :(
