### ISSUE TITLE
Missing Controller

### ISSUE THREAD

**Issue by danijel88** [jasontaylordev/CleanArchitecture#138]
**In existing project I had couple of new ApiControllers, from where last two controllers VersionController and TestController are not displayed in NSWAG.**

**Expected behavior**

**Screenshots**
https://i.imgur.com/nXgNbk8.png
Missing in NSWAG: https://i.imgur.com/TPyxV1A.png
Even if there is in specification.json

Any idea why this is happening ?

Here is the link of my code: https://github.com/danijel88/CleanArchitecture

Thanks

**Comment by nikibreg** [comment]
I had the same problem and I fixed it by uncommenting the NSwag command inside the WebUI.csproj file.

**Comment by danijel88** [comment]
> I had the same problem and I fixed it by uncommenting the NSwag command inside the WebUI.csproj file.
> Also, make sure to hard reload your Swagger doc (CTRL+SHIFT+R on Windows).

It is already uncommented. For some reason only 5 API it is displayed, I had remove one and immediately appear another one...

**Comment by jasontaylordev** [comment]
Taking a look now, thank you for putting together a sample repo.

**Comment by jasontaylordev** [comment]
Hi @danijel88. Thanks for reporting this issue. I've checked the following:

 - Clone and build ✔
- NSwag running ✔
- Generate specification.json correctly ✔
- Launch the project from VS 2019 using CTRL + F5 ❌

When I launch the project I get the following error:
```
An error occurred while starting the application.
InvalidOperationException: No service for type 'Microsoft.Extensions.Logging.ILogger' has been registered.
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)

InvalidOperationException: No service for type 'Microsoft.Extensions.Logging.ILogger' has been registered.
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<T>(IServiceProvider provider)
Audit.WebUI.Program.Main(string[] args) in Program.cs
+
                    var logger = scope.ServiceProvider.GetRequiredService<ILogger>();
Audit.WebUI.Program.<Main>(string[] args)
```

This exception is happening in Program.cs in the catch block, so the application is failing to start. Sadly, it's also failing to get a logger to log the error, so it just results in complete failure with no useful information provided to you. This is because of a bug that has been fixed in the latest version of the template. 

Please fix it in your version as follows:

Remove the static modifier from the program class:
    ```
    public static class Program
    ```

Update line 40 as follows:
    ```
    var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();
    ```


This startup error was a lucky find, it was simply because your connection string referenced **sbr-p021\\sqlexpress**. The real error was:

```
SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
```

- Fix Program.cs and connection string then re-launch the project from VS 2019 using CTRL + F5 ✔
- Navigate to https://localhost:44312/api (Swagger UI) and verify correct endpoints ✔

I expected to see an issue here, assuming that the previous issue was unrelated to your issue. But when I browse Swagger UI everything looks normal. I can see the following endpoints:

![image](https://user-images.githubusercontent.com/1988321/82207607-7274a500-994d-11ea-8b62-b268079de177.png)

Nothing seems to be missing. Please can you try again, maybe fixing the Program.cs error first, and let me know what you find.

**Comment by danijel88** [comment]
@jasontaylordev Thanks for your time.
Launch the project from VS 2019 using CTRL + F5 or F5(debug with breakpoints on line 40 in Program.cs )  from my side it works, I'm not getting any error which you wrote, strange, but true...
Only what I'm getting from console is this(still didn't do modification which you suggested.) : https://i.imgur.com/tNJxG0r.png

After updates suggested by you:
No more  error from picture above, but still not visible all ApiControllers, example it is missing WheatherForecastController.

https://i.imgur.com/U5e9bOw.png

In my repo under project WebUi, I create new file DebugOutput.txt where I had copy all lines from output. In order to see what happens from running application till it is not closed.

Thanks,
Danijel

**Comment by jasontaylordev** [comment]
> @jasontaylordev Thanks for your time.
> Launch the project from VS 2019 using CTRL + F5 or F5(debug with breakpoints on line 40 in Program.cs ) from my side it works, I'm not getting any error which you wrote, strange, but true...

I get the error only because your database connection string is not valid for me.

> Only what I'm getting from console is this(still didn't do modification which you suggested.) : https://i.imgur.com/tNJxG0r.png

This is a different issue. It's just ASP.NET Core waiting for Angular to start. Hopefully, MS will improve this in their SPA template soon.

> After updates suggested by you:
> No more error from picture above, but still not visible all ApiControllers, example it is missing WheatherForecastController.
> 
> https://i.imgur.com/U5e9bOw.png
> 
> In my repo under project WebUi, I create new file DebugOutput.txt where I had copy all lines from output. In order to see what happens from running application till it is not closed.

I've reviewed DebugOutput.txt but can't see the issue. You can see that I am not experiencing this issue as WeatherForecast is visible.

Also, if I take the specification from your repo, and paste it into https://editor.swagger.io/ I can see the WeatherForecast endpoint there too. Try for yourself.

I don't think this is an issue with the template, possibly something weird with SwaggerUI or your browser.

**Comment by danijel88** [comment]
Hi,
Sorry for late replay it is fixed, I had manage from angluar side to hide those progress form console.
Actually after I changed Program.cs i got all Controllers.
Thanks for help.
Danijel
