### ISSUE TITLE
[Question] Is there a way to keep the seeded data in the integration tests

### ISSUE THREAD

**Issue by AlQuraian** [jasontaylordev/CleanArchitecture#144]
I liked the recent changes to include a real database for testing. However, after migrating my code to be the same. It seems that Respawn deletes the seeded data on rest. The only way I was able to avoid this is by ignoring the tables, i.e. adding them to 'TablesToIgnore'.

Is there a better way to reseed the database?

Thanks a lot!

**Comment by jasontaylordev** [comment]
HI @AlQuraian - thanks for the feedback and great question. You've probably worked it out by now but I'll respond anyway for future readers. The reason that the database is completely reset (aside from ignored tables) is so that your tests do not rely on global data. This data could change in the future, resulting in broken tests for the wrong reason, i.e. the behaviour isn't broken it's just that some nasty person changed the global test data and now you have to fix it. So you avoid this whole issue but just setting up the data you need within each test. Hope this helps.
