### ISSUE TITLE
 Application startup exception System.InvalidOperationException: Key type not specified.

### ISSUE THREAD

**Issue by nagtilaklaxman** [jasontaylordev/CleanArchitecture#149]
Application startup exception
System.InvalidOperationException: Key type not specified.
   at Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ConfigureSigningCredentials.LoadKey()
   at Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ConfigureSigningCredentials.Configure(ApiAuthorizationOptions options)

**To Reproduce**
1.  after dotnet run command

**Expected behavior**
should run the application

**Screenshots**
![image](https://user-images.githubusercontent.com/16507190/82916490-72ac1a80-9fb5-11ea-81a2-25276500df5a.png)

**Additional context**

**Comment by xontab** [comment]
This usually happens when the `Key` options are missing in `IdentityServer`.  

When running the application in Development mode (via `ASPNET_ENVIRONMENT=Development` environment variable) the `appsettings.Development.json` will be applied which includes the following configuration.  This will create adhoc certificates which cannot be used in Production.  

```
  "IdentityServer": {
    "Key": {
      "Type": "Development"
    }
  }
```

Thus for Production mode, you will need to load your own certificate using the following application settings. Sample below. For more details on different key types - https://stackoverflow.com/questions/57246219/how-to-configure-key-settings-for-identityserver-in-appsettings-json-for-aspnet

```
  "IdentityServer": {
    "Key": {
      "Type": "Store",
      "StoreName": "My",
      "StoreLocation": "CurrentUser",
      "Name": "CN=MyApplication"
    }
```

**Comment by jasontaylordev** [comment]
Closing, but just in case anyone needs additional guidance - https://github.com/jasontaylordev/CleanArchitecture/issues/80#issuecomment-605941356.
