### ISSUE TITLE
[Question] Mapping ApplicationUser to List

### ISSUE THREAD

**Issue by meekcg** [jasontaylordev/CleanArchitecture#164]
Hi

How do you map a list of ApplicationUsers if you cannot `public class UserListDto : IMapFrom<ApplicationUser>` in the Application layer

```
// Infrastructure/Identity/IdentityService.cs
var users = await _userManager.Users
    .ProjectTo<UserListDto>(_mapper.ConfigurationProvider)
    .ToList();
```

Thanks

**Comment by AlaaL** [comment]
Hi,
why the issue is closed did you know the answer ? 
because i want to to the same thing now.

**Comment by wahidrezgui** [comment]
Hy @AlaaL  I think since you have Applicationuser in infrastructure you can use it in you UI/api layer without referencing Application Layer ,Add your Dto inside infrastructure layer where you have all the service required for manipulating ApplicationUser.

**Comment by Arebisc** [comment]
I've also run into this trouble. Let's say I want to have handler that will return all users by some criteria. How to achive it? I've been thinking about some `IUser` interface (that will be implemented by ApplicationUser) in application layer so that I can later declare method in `IIdentityService` that will return `Task<IEnumerable<IUser>>` . 

I think that this `IUser` interface is not something that we can pass to Domain project.

**Comment by bramburn** [comment]
I would just create a entity then fill it in, it sounds you're coupling the identityuser to the application.

If you think about it different domains would need different user information, so each one would need to have their DB to deal with it.
e.g.

marketing would use:

- first name, lastname
- email
- accounts
- phone number
- activity.....

whereas operation might just need:

- firstname, lastname,
- email
- delivery address
- phone number


so when you setup your CQRS they would each have different entities to fill in.

use and create API between the projects, separate your login and use identityserver, and each project would be clients to the identityserver that just deal with username, password, roles.
