### ISSUE TITLE
Clean Architecture Deployment in Azure

### ISSUE THREAD

**Issue by ralpholazo24** [jasontaylordev/CleanArchitecture#169]
Is there any tutorial on how to deploy this on microsoft azure?

**Comment by GFoley83** [comment]
There's are no special considerations when deploying the solution to Azure; it's a standard .NET Core solution.

Similar question was already asked and answered here:
https://github.com/jasontaylordev/CleanArchitecture/issues/80#issuecomment-605941356

**Comment by workcontrolgit** [comment]
I did experiment with the deployment with the backend is MS SQL SaS to Azure from Visual Studio 2019 Community.   Here are the steps

1. Create app service and download the publishing profile
2.  Setup connection string in the app service to point to MSSQL SaS DB
3. In VS Studio, publish the app to Azure using the publishing profile (in step 1)

Issues I ran into
1.  Identify server certificate error (HTTP error 500.30 error code) - since it is for experimentation, I changed the IdentityServer setting in the production appsettings.json the same as the development (not require cert)
2.  SQL Server firewall error (also shown as HTTP error 500.30) - updated the MS SQL server firewall/IP restriction to allow App Service to access the database server.   

Disclaimer - The above instructions are for development proof of concept only.

**Comment by ralpholazo24** [comment]
For my updates, I can now deploy the app on Azure VM using IIS but I am experience error if I am trying to log in.

I have an error when calling the connect/token api.

Here are my parameters.

![image](https://user-images.githubusercontent.com/18304032/85846195-1157b100-b7d8-11ea-9744-20e8aab7a939.png)
![image](https://user-images.githubusercontent.com/18304032/85846227-19afec00-b7d8-11ea-99de-6bcfbad7e175.png)

**Comment by workcontrolgit** [comment]
The form data looks right.  400 error is tricky as it could be on the client and server.  Maybe clear cookie and also check the IIS server log.

**Comment by GFoley83** [comment]
Have you configured IdentityServer correctly for the environment? 
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1#deploy-to-production

You might have more luck on StackOverflow, which is the best forum for questions like this.

**Comment by akqira** [comment]
Hi @ralpholazo24 
To share my experience, i've got the same issue on Azure and not locally. After some investigations i found that my Current Plan for the App Service (shared free instance) does not allow me to read my certificate file in order to sign the token.
This is a limitation by Microsoft, one of the solutions is to upgrade to basic plan

https://github.com/dotnet/runtime/issues/30658#issuecomment-523987878

Regards

**Comment by jasontaylordev** [comment]
Closing (as covered in #80), but I promise to write a guide soon. ❤
