### ISSUE TITLE
Why UI depends on infrastructure?

### ISSUE THREAD

**Issue by artyomabrahamyan** [jasontaylordev/CleanArchitecture#186]
Usuall approach for clean architecture is that both Infrastructure and UI depend on business. Here UI also depends on Infrastructure, how would you suggest to overcome that issue. 

Thanks.

**Comment by Leanwit** [comment]
Hello artyomabrahamyan
You can find the answer in the readme.

> WebUI
> This layer is a single page application based on Angular 9 and ASP.NET Core 3.1. This layer depends on both the Application and Infrastructure layers, however, the dependency on Infrastructure is only to support dependency injection. Therefore only Startup.cs should reference Infrastructure.

**Comment by artyomabrahamyan** [comment]
Hi @Leanwit, thank you for response. 

Let me reformulate my question. Do you see anyway to acheive this without having Infrastructure references in the Web UI project?

> In order to wire up dependency injection in ConfigureServices in the Startup.cs file of the UI project, the project may need to reference the Infrastructure project. This dependency can be eliminated, most easily by using a custom DI container. For the purposes of this sample, the simplest approach is to allow the UI project to reference the Infrastructure project.

Here microsoft states that it is possible to acheive with DI container.
https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures#clean-architecture

Any suggestions on this?

**Comment by GFoley83** [comment]
The only alternative is to load DLLs using assembly scanning instead of having a hard project reference
E.g https://autofaccn.readthedocs.io/en/latest/register/scanning.html

Given your MVC/Web API/Azure Func projects are your entry point into your whole solution, the composition root (Startup.cs) has to have references to required projects somehow. Given the logic is isolated to here (where it's supposed to be), there shouldn't be an issue.

**Comment by artyomabrahamyan** [comment]
Thank you for clarification.
