### ISSUE TITLE
How to access RelationalQueryableExtensions (FromSqlRaw) from IApplicationDbContext

### ISSUE THREAD

**Issue by ShamalFdo129** [jasontaylordev/CleanArchitecture#190]
RelationalQueryableExtensions  FromSqlRaw and other extension method can not be accessed from IApplicationDbContext object in our commands and queries.
is there anyway to extend these extension method into IApplicationDbContext?

**Comment by MCCshreyas** [comment]
Hi @ShamalFdo129 . I haven't used those extension methods from `RelationalQueryableExtensions` in my projects yet. But what I noticed that by looking at the documentation which is [here ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalqueryableextensions?view=efcore-3.1) is that those extension methods do work on `DbSet<T>` and we already have that in `IApplicationDbContext`, so ideally you can access those extension methods on your Db sets in your commands and queries.
Just check are you missing any using statements because of which you are not able to access those extension methods?
Thanks.

**Comment by ShamalFdo129** [comment]
@MCCshreyas 
not sure what is going on here. I have namespace "using Microsoft.EntityFrameworkCore" but extension methods are not access
![Untitled](https://user-images.githubusercontent.com/34286807/87964124-5e792b00-cad7-11ea-9ae2-389cfefc5fda.jpg)
ible.

**Comment by ameyvaidya** [comment]
Is method `FromSqlRaw `available in `IApplicationDbContext `interface?

**Comment by jasontaylordev** [comment]
The implementation for `FromSqlRaw` would come from the chosen provider package, e.g. Microsoft.EntityFrameworkCore.SqlServer. In order to use it in the Application layer, you would therefore need a reference to Microsoft.EntityFrameworkCore.SqlServer. 

I'd advise against this as it would result in the Application layer being dependent on the underlying database. Instead, compose and execute your SQL queries within the Infrastructure layer, accessible via an interface created in the Application layer.
