### ISSUE TITLE
Removing Infrastructure dependency from Presentation

### ISSUE THREAD

**Issue by rinoreji** [jasontaylordev/CleanArchitecture#2]
Creating a separate class library which handles all DI could possible remove direct Infra dependency from WebUI. Share your thoughts

**Comment by jjz4689** [comment]
Totally agree. Just watched the [NDC Sydney Conf 2019](https://youtu.be/5OtUm1BLmG0) video (great talk by the way, Jason) and thought exactly the same thing.

I suppose there are 2 obvious approaches to this:
1. the DI lib just calls the existing relevant `.AddXyz()` extension methods for each other layer; or
2. the DI lib does the heavy lifting and contains relevant registration logic that's in all the other `.AddXyz()` extension methods, stripping some/all logic out of there.

Both approaches involve the DI class library referencing the other necessary libs (except WebUI, as this can register its own services). Then, WebUI (and by extension, any other Presentation projects) just calls a setup method on the DI class library.

For me, I guess it's a mix of both approaches, as some setup is relevant to each library, and can be encapsulated as such; however, I think some bits might be able to be pulled out to the DI layer.

The reason I say this is the Infrastructure project relies on a connection string being named `DefaultConnection` in the config of the assembly running the code. I guess I'm splitting hairs, but perhaps this could be passed into the Infrastructure's `.AddXyz()` setup method, to ensure a bit of flexibility in future?

Another question (if Jason wanted to bring this up in his talks) would be how do we visually represent this "layering"? Is the DI lib a "sideways" segment of the layer at Infrastructure/Presentation level? Is it a thin layer between a Presentation and the rest of the architecture?

On balance, playing devil's advocate: is this splitting the DI into its own library even a good thing at all?

Just some ideas, throwing a few thought experiments around.

Feel free to critique/add your thoughts.

**Comment by chuksogbolime** [comment]
I particularly find this discussion quite interesting as the first thing that came to mind while watching the video when Jason mentioned that Presentation and Infrastructure layers should not depend on each other was "DI". I went on to look at the implementation and it became obvious that this separation may only be "wishful". So the question here is how do you achieve this separations in "Clean Architecture" while keeping in mind the "Entourage Anti-Pattern". I think the DI class was kept in the Infrastructure layer as a necessary evil.

**Comment by bbarry** [comment]
This is something I've been struggling with as well: nobody seems to test their Startup or Program class; just taking for granted that if the application is running, that code must be correct and bug free? 

This is wrong. We all make mistakes, registering singletons that depend on transient classes or letting some logic creep in to our startup code over the years. It seems clear that the root of the problem is that we have this component of our code that is fundamentally untestable because it depends on something we haven't defined in our model.

I would represent it as a Host or Environment layer outside of the existing layers. 

I sorta think it is not appropriate for the presentation layer to contain the DI root but I don't know enough about the startup sequence of .net core to suggest how to fix it. Ideally Program and Startup are not in WebUI (at least not as they are now).  They are part of the environment that enables the presentation layer and not part of the presentation layer itself.

**Comment by jasontaylordev** [comment]
Apologies for the delay, I am trying to catch-up and stay on top of these issues so I can focus on adding new features! 😀

The reference from Presentation to Infrastructure exists only for the purposes of dependency injection. Therefore, Infrastructure should only be referenced within Startup (WebUI). If it appears anywhere else, we know this is a problem (managed using pull requests).

In addition, to help ensure that Startup doesn't become bloated with service registrations I've created `IServiceCollection` extensions methods within Application and Infrastructure (see DependencyInjection.cs). 

I am relatively happy with this approach despite its apparent limitations. It is working well within my team. When that ceases to be the case, I will look for an alternative solution.

Regardless, I'd love to hear any recommendations for a simple and clean approach that manages service registration in a separate project. 😀
