### ISSUE TITLE
Using the MappingProfile class across several projects

### ISSUE THREAD

**Issue by MCKRUZ** [jasontaylordev/CleanArchitecture#206]
I may just be incredibly dense here but I'm wondering if there is a way to utilize the MappingProfile code across other projects.  So the way that this CleanArchitecture template is setup there is a single Application project that holds all of the Command and Queries.

There is a class called MappingProfile that will automap all of the classes for you, which is great!  

But if you have Commands and Queries across several projects I find I have to replicate that class on every project.  Is there a better way to do this?

**Comment by GFoley83** [comment]
The general idea is to keep the commands and queries together in the application project and not split them across multiple projects.

**Comment by vyliniem** [comment]
Not sure if this is what you are looking for, but I used the MappingProfile/IMapFrom in another project where I don't use commands/queries but have multiple runnable apps with different mappings. I put the MappingProfile/IMapFrom into a shared project, but also had to change the "ApplyMappingsFromAssembly" line into:

`ApplyMappingsFromAssembly(Assembly.GetEntryAssembly());`

Otherwise it tries to find the mappings inside the shared project. In the application startup-files I add the AutoMapper with line:

`services.AddAutoMapper(typeof(MappingProfile));`

**Comment by jasontaylordev** [comment]
Good solution @vyliniem, thanks for sharing. 👍 

Agree with @GFoley83. Think of the commands and queries as simply the entry points to Core, kind of how the actions are the entry points to Web API apps.
