### ISSUE TITLE
Build Error - Bad Imports under Linux

### ISSUE THREAD

**Issue by Fumeaux** [jasontaylordev/CleanArchitecture#208]
**Describe the bug**
The Project could not be built.

**To Reproduce**
1. Download the template
`cd bla/bla/CleanArchitectureSolution`
`dotnet new -i Clean.Architecture.Solution.Template`
`dotnet new ca-sln`
2. Open the template in Rider IDE
3. Build succeeds
4. Running the Application results in an Error (see below)

**Expected behavior**
The Template should work without modification out of the box

**Screenshots**
![Screenshot_20200808_101109](https://user-images.githubusercontent.com/49806453/89705705-a0bbbc80-d95f-11ea-9135-01ae0d608b35.png)

**Additional context**
Manjaro (5.4.52-1-MANJARO)
-> dotnet-sdk (3.1.3.sdk103.2-1)
-> nodejs-lts-erbium (12.17.0-1)
Rider IDE (2020.1.4)

Changing those two lines fixed the error and everything worked fine afterward.

**Comment by Fumeaux** [comment]
Strangely enough, when pulling the branch to fix the problem the import worked without a problem.

**Comment by jasontaylordev** [comment]
This has to do with how the .NET Core Project template renames everything matching CleanArchitecture based on your chosen solution name (generally the root folder name). One fix would be just to name `cleanarchitecture-api.ts` so that it doesn't match the template name. Any suggestions? Maybe `generated-api.services.ts`?
