### ISSUE TITLE
[Question] Reuse of Fluent Validation Rules

### ISSUE THREAD

**Issue by GururajNadager** [jasontaylordev/CleanArchitecture#209]
I am adding additional layers to the Clean Architecture Template  and am using the below solution structure,
MVC Application --> API Layer --> Application Layer --> Domain Layer

In MVC Application i have a ViewModel and when passing to API Layer i am converting it to DTO. Now how and where do i implement  Validators to avoid duplication of Rules.
For ex:

**MVC Layer**

```
public class StudentViewModel
{
    public string Name{get;set;}
}

public class StudentValidator : AbstractValidator<StudentViewModel> 
{
          public StudentValidator()
        {
            this.RuleFor(x => x.Name).Empty();
        }
}
```

**Application Layer**
```
public class CreateStudentCommand:IRequest<int>
{
  public string Name{get;set;}
}
public class CreateStudentCommandValidator : AbstractValidator<CreateStudentCommand> 
{
          public CreateStudentCommandValidator()
        {
            this.RuleFor(x => x.Name).Empty();
        }
}
```

**Comment by MCCshreyas** [comment]
Hi @GururajNadager. I think there is no point in adding a new presentation layer to the project. Because the API project is a presentation layer. 
If your requirement is that your project is having both an MVC application (Website) and an API side (which will consume by mobile apps I guess), then you can add to the same API project. The ASP.NET Core templates are quite flexible; you can have both API and MVC applications in a single project, no need to have a separate project which will add unwanted complexity.

**Comment by GururajNadager** [comment]
Hi @MCCshreyas . I agree with your point.

Considering a situation where i need to totally decouple my MVC application  from my API layer or  if the application is built on older .NET frameworks . In that scenario how can we handle this?

**Comment by MCCshreyas** [comment]
What I will do is, I will keep validation related to view thing like required fields and other similar validation to ViewModel only and will have business validation rules in Application layer, because at the end ViewModel data will be posted to Application layer. 
And also I this way I can keep my business validation rules in Application layer regardless of which presentation layer I am using, because Application layer should not know from whare the request is coming, because applications layer only concern about request and not the one who originated the request whether it's an API or an MVC app!
