### ISSUE TITLE
Not allowed to reference Application project

### ISSUE THREAD

**Issue by jgondev** [jasontaylordev/CleanArchitecture#218]
I'm experiencing issues when using the template. Both using the latest repo version or the **cs-sln** template.

I'm "not allowed" to reference the Application project. I'm kind of blocked since I cannot understand what's happening. 

Everything seems to be fine, but same issue appears in both situations.

![image](https://user-images.githubusercontent.com/22662179/90567171-0bfc5e80-e1aa-11ea-9334-356e8f18363f.png)

```
PS > dotnet --info                                                       
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    5b6f5e5005

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  2.1.511 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
```
```
PS > node -v
v12.18.3
```

Am I doing anything wrong?

Thanks

**Comment by jgondev** [comment]
It worked after changing the TargetFramework of Application project from `<TargetFramework>netstandard2.1</TargetFramework>` to `<TargetFramework>netcoreapp3.1</TargetFramework>`

**Comment by damikun** [comment]
Template is made for netcoreapp3.1

**Comment by jasontaylordev** [comment]
Hey @jgondev - apologies, I've no idea why you're getting that issue. I tried `dotnet new ca-sln` followed by `dotnet build` and `dotnet test`. Build successful and all tests passing. I didn't need to change target framework. Did you learn anything new since you raised the issue?

I also made sure I had the latest template with `dotnet new --install Clean.Architecture.Solution.Template`.
