### ISSUE TITLE
Merge TestBase and Testing

### ISSUE THREAD

**Issue by elken** [jasontaylordev/CleanArchitecture#222]
**Is your feature request related to a problem? Please describe.**

The resources needed during the IntegrationTests are already defined as static, so the boilerplate of `using static Testing` seems redundant.

**Describe the solution you'd like**

- Rename `Testing` to `TestStartup`
- Remove references of `using static Testing`
- Make `TestBase` inherit from `TestSetup` and add a `[TestFixture]` attribute

**Additional context**

From my testing it looks as if it muddles the namespacing of the tests (according to Resharper/Rider, VS Test Explorer seems to handle it fine), so perhaps more experienced NUnit experts can weigh in on a better solution.

**Comment by jasontaylordev** [comment]
Testing manages the initialisation of global test resources and provides utilities to work with those resources. Giving these behaviours, I don't feel that TestStartup would be a better name. I can't think of a better name. 

I like the using static directive because it allows access to the utilities (mentioned above) without needing to specify the testing name. 

The TestBase class is a TestFixture that is responsible for resetting the database state before a test runs. The intent is that other test fixtures inherit from this class, to avoid duplicating this behaviour. 

I have renamed TestBase to BaseTestFixture. I have also changed it to abstract and marked the class with the TestFixture attribute (although this is optional). This should convey the intent a little more clearly.

Thanks for raising this issue, hopefully these changes will make the intent clearer.
