### ISSUE TITLE
Multiple IMapFrom<T> : Ambiguous match found exception

### ISSUE THREAD

**Issue by caz3542** [jasontaylordev/CleanArchitecture#275]
The AutoMapper auto config fails when you try to map to more than one type. For instance:

TodoListDto : IMapFrom<TodoList>, IMapFrom<TodoList2> will fail with an System.Reflection.AmbiguousMatchException: 
Ambiguous match found exception. 

This is not an issue if you have a 1:1 model, but if you have to map to 1:Many models this causes issues. In my case I want to write the same item to different databases requiring different database models.

**Comment by jasontaylordev** [comment]
HI @caz3542 - thanks for reporting this issue. You're right, this is not well supported. At this stage, I'm not looking to add support, not because it isn't a good feature, just because I have to stop somewhere. I want the template to be simple and therefore easy to understand. If I try to cater to everything, I think this would be a step in the wrong direction. Thanks anyway.

**Comment by caz3542** [comment]
Thanks for the update and completely understand. Did like that specific feature though.
