### ISSUE TITLE
Calling commands from internal components

### ISSUE THREAD

**Issue by hypervtechnics** [jasontaylordev/CleanArchitecture#29]
I have a `DeleteDailyCommand` and sending it via MediatR from an app-internal Quartz scheduler. But all pipeline behaviours relying on the http context fail, as its not available during the internal send. How would you call system internal commands or bring them into this architecture?

**Comment by JasonGT** [comment]
Hi @hypervtechnics. Application layer / pipeline behaviours shouldn't know anything about the HttpContext, it's not a dependency. Please can you share more info about the issue?

**Comment by hypervtechnics** [comment]
Hi, the dependency is indirect and comes along with the current given implementation of e.g. the current user service, which accesses the HttpContext. During logging of the username an exception occurs as the identity service can't find the non-existent user. This can be solved by simply removing the username in general, but I'd consider this only as a work around.

The thing is now: I have job executed every day via Quartz. During this a scope in DI gets created, a mediator instance will be requested and a message like DeleteDailyCommand will be sent through it. The command is only for app internal use and not accessible via a controller or in general from the outside. Now I constantly got exceptions in the logging behavior as the information is not available (like with an anonymous request). As a temporary solution the behaviour checks first if the given request is of type DailyDeleteCommand and if yes skips the logging part and continues with the pipeline.

So: The behaviours (like Validation or request logging) are only relevant for IRequest coming from the WebApi. I added a behaviour which also checks a header (via interface but in the end it accesses the http context).

Is this a wrong approach? Is there a specific way to put those app-internal logic?

Typical disclaimer: Sorry if it sounds confusing ;)

**Comment by jasontaylordev** [comment]
Again, sorry for the delay. I am sure you have figured out a solution by now. I am assuming that your scheduling services are running as a console app, a windows service, or something similar. When you wire-up dependency injection for the program, you would need to specify an implementation for ICurrentUserService, since you won't be using the WebUI implementation. You will need to create your own. I would suggest creating a system user account and specifying that user Id as within your implementation of CurrentUserService. This way your internal system process will be running as a system user.

The benefit is that you will still be using the same pipeline. So when things go wrong, you will be able to check out the logs for request info and unhandled exceptions.

Hope this helps. Let me know if you need further clarification.

**Comment by hypervtechnics** [comment]
I did figure out a rather good solution. I just removed all of the pipeline behaviors. The scheduler (Quartz) is running in the same process and the scheduler service (e.g. to dynamically add job) is injected into the DI container within the Infrastructure. Doing the approach you mentioned is a good approach. But not doable when used in the same DI container as it would require different implementations of the same interface and injected based on a condition. Only possible with a factory pattern or named services (?) which would introduce a lot of boilterplate code within the constructors.
