### ISSUE TITLE
[Question] How to define same entity configuration/validation in the whole solution

### ISSUE THREAD

**Issue by alecasciaro** [jasontaylordev/CleanArchitecture#295]
In the Infrastructure layer, using the IEntityTypeConfiguration it's possible to define the entity configuration. 

For example refering to TodoList entity

**TodoListConfiguration**

```
public void Configure(EntityTypeBuilder<TodoList> builder)
{
      builder.Property(t => t.Title)
          .HasMaxLength(200)
          .IsRequired();

      builder
          .OwnsOne(b => b.Colour);
}
```
It set the table column _Title_  length to 200 characters (nvarchar(200)).
This means that we need to create a validation that follows that constrain.
This is done by two validators in the application layer

**CreateTodoListCommandValidator**

```
  public CreateTodoListCommandValidator(IApplicationDbContext context)
  {
      _context = context;

      RuleFor(v => v.Title)
          .NotEmpty().WithMessage("Title is required.")
          .MaximumLength(200).WithMessage("Title must not exceed 200 characters.")
          .MustAsync(BeUniqueTitle).WithMessage("The specified title already exists.");
  }

```
**UpdateTodoListCommandValidator**

```
public UpdateTodoListCommandValidator(IApplicationDbContext context)
{
    _context = context;

    RuleFor(v => v.Title)
        .NotEmpty().WithMessage("Title is required.")
        .MaximumLength(200).WithMessage("Title must not exceed 200 characters.")
        .MustAsync(BeUniqueTitle).WithMessage("The specified title already exists.");
}
```
This eventually affects also the tests.

As you can see there is code duplication. 

` .MaximumLength(200).WithMessage("Title must not exceed 200 characters.")`

It's needed to specify the behavior multiple times.
The duplication increase according to the validation needed.

Has anyone figured out how to use a common validator or is really useful a common validator?

**Comment by Sokoo92** [comment]
What we did was create constants in the Domain layer, either within the Domain class/file itself, or seperated, doesn't really matter. But this way we have all the configuration values in one place per domain. And we reference those in the configuration and in the validators, this way there won't be any confusion and mismatching numbers/values for the configuration and validators. This does indeed not overcome the fact that you are still duplicating some what of your code, but in this case, I wouldn't mind that. The values for both will stay consistant and you can also reference those in your tests.

`.MaximumLength(TodoListConstants.MaximumLength).WithMessage(TodoListConstants.MaximumLengthErrorMessage)`

**Comment by MCCshreyas** [comment]
You are mixing two things, `TodoListConfiguration` is configuration for domain model (table schema).
And request validator are different things, sometime those can be same but not all of the time! We validate incoming request with those validator before hitting database!

**Comment by rafaelfgx** [comment]
You can do it this way below:

```
public abstract class UserCommand
{
    public string FirstName { get; set; }

    public string LastName { get; set; }
}

public sealed class AddUserCommand : UserCommand { }

public sealed class UpdateUserCommand : UserCommand
{
    public int Id { get; set; }
}

/// In this class are all common rules
public static class UserRules
{
    public static IRuleBuilderOptions<T, int> Id<T>(this IRuleBuilder<T, int> ruleBuilder) => ruleBuilder.NotEmpty();

    public static IRuleBuilderOptions<T, string> FirstName<T>(this IRuleBuilder<T, string> ruleBuilder) => ruleBuilder.NotEmpty().Length(3, 50);

    public static IRuleBuilderOptions<T, string> LastName<T>(this IRuleBuilder<T, string> ruleBuilder) => ruleBuilder.NotEmpty().Length(5, 200);
}

public sealed class AddUserCommandValidator : AbstractValidator<AddUserCommand>
{
    public AddUserCommandValidator()
    {
        RuleFor(x => x.FirstName).FirstName();
        RuleFor(x => x.LastName).LastName();
    }
}

public sealed class UpdateUserCommandValidator : AbstractValidator<UpdateUserCommand>
{
    public UpdateUserCommandValidator()
    {
        RuleFor(x => x.Id).Id();
        RuleFor(x => x.FirstName).FirstName();
        RuleFor(x => x.LastName).LastName();
    }
}
```

**Comment by jasontaylordev** [comment]
Implementing the same validation across all layers of the solution is not possible unless a different approach is used. 

For example, using data annotations on the domain model and using the domain model all the way from the front end to the back end.

For a trivial application this may be suitable, but in most cases it would be very limiting and require most logic to be written in the UI. 

Rather than attempting to have the same validation across all layers consider this approach. 

The database is responsible for maintaining integrity of the data, and therefore ensures that only valid data is stored. You just need to make sure you've configured you domain model correctly. 

The inputs to commands and queries must be validated. These requests represent the entry point to core. Using FluentValidation effectively, as demonstrated above, can help to reduce duplication of code. Having said that, command and query should represent a distinct and separate use case, and is not always beneficial to share code between uses cases. Doing so can actually increase complexity and the risk of breaking changes.

If you consider this approach, then validation only occurs in one part of the application, the entry point to core. The enforcing of constraints is managed by the database, not our code, based on our configuration of the data model. This is a clean and simple approach, for a sufficiently complex problem. 

Happy coding! 😀
