### ISSUE TITLE
Remove the Identity Server implementation from the solution

### ISSUE THREAD

**Issue by kodaren** [jasontaylordev/CleanArchitecture#302]
Thank you first for your excellent work on Clean Code architecture and the VS template.

However, not everyone want to use an integrated identity server. Many companies and usually enterprises require a separate identity solution. In our case, we need to use an existing single sign-on solution (IdentityServer 4 server), which is used by multiple applications. 

Even if you for the sample want to use an integrated identity server, it should be possible to easily remove it and use another server for the login.

**Comment by baratgabor** [comment]
Sounds like a good idea to make it at least 'pluggable'. I think the Infrastructure layer and the Startup could generally use some sort of modularization pattern.

Maybe it's kind of a shameless plug, but I personally implemented a crude modularization in my own Clean Architecture sample project that is largely based on this template; if anyone is interested, you can look into it here (basically all root folders in Infrastructure contain a Startup.cs that is called by the Infrastructure root's Startup.cs):
https://github.com/baratgabor/MyWarehouse

One difficulty is that there are some interrelated aspects of the configuration between Identity, EF Core and the authentication solution we are using. That might prevent perfect modularization. But at the same time I think it shouldn't pose a difficulty in making at least Identity Server alone pluggable.

I actually left out Identity Server and just wrote a simple JWT token generator and a crude authentication service, because I generally dislike including something as heavyweight as IS just for basic authentication.

**Comment by kjartanvalur** [comment]
I agree with @kodaren 
It would be nice to see identity server (login page) in a seperate project in this solution not combined with UI. Then it´s more pluggable and easy to switch for something else.

**Comment by jasontaylordev** [comment]
This is something I might look at doing in the future, but not for the time being. Thanks for the suggestion.
