### ISSUE TITLE
[Question] How to add custom claims?

### ISSUE THREAD

**Issue by shobhitvaish** [jasontaylordev/CleanArchitecture#318]
Greetings, 

1. I am using the ASP.net identity framework, not the identity server. 
2. I have created a separate project - infrastructure identity layer 
3. I have interfaces defined in the application layer, and implementation related to identity resides in the infrastructure identity layer.

Based on business rules, I need to add custom claims during user sign-in, and I know I can implement/derive UserClaimsPrincipalFactory([ref](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.userclaimsprincipalfactory-2?view=aspnetcore-5.0) and [ref](https://www.nooglesoft.com/blog/custom-claims-transformation-in-aspnet-core-identity)) in the infrastructure identity layer, but this means my business logic is now in the infrastructure identity layer. 

I can also derive from UserClaimsPrincipalFactory in the application layer, but then I need to add the asp.net identity package reference to the application project, which means my application project is now dependent on a particular framework.

Any ideas on how to solve this?

I really appreciate any help you can provide.

**Comment by neman** [comment]
I used [IClaimsTransformation Interface](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.iclaimstransformation?view=aspnetcore-5.0) for that purpose.
Just implement that interface with your class.

I had windows authentication and had to add my custom claims from database. I mixed them together within implementation of IClaimsTransformation. You should read claims from cache, since IClaimsTransformation triggered on each request, as I remeber.

**Comment by s-whaley** [comment]
I've used a custom ProfileService similar to what is referenced in this issue #50

**Comment by shobhitvaish** [comment]
@s-whaley Thanks for your reply, but IProfileService is specific to the identity server, which I am not using.

**Comment by shobhitvaish** [comment]
Did anyone get a chance to look into this?

**Comment by jasontaylordev** [comment]
Closing, as not specific to the template. However, I do add custom claims in this project - https://github.com/jasontaylordev/flexible-aspnetcore-authorization. Good luck.

**Comment by achmstein** [comment]
Hi Jason,

I'm using the same thing you used in flexible authorization project. 

I'm using Blazor with CleanArchitecute template. I defined Permissions enum in the Security folder in Application layer to protect my commands and queries. 

I copied the Permissions enum to the Web.Shared folder to protect Blazor pages and components because I don't want to reference the Application layer from Web.Shared project. Is that the right approach? or should I define Permissions enum in another place?

Also I defined PermissionAuthorizationHandler and PermissionAuthorizationRequirement in the Web.Shared project to be used by both the Server and Client like you did. 

Thanks

**Comment by jasontaylordev** [comment]
> I copied the Permissions enum to the Web.Shared folder to protect Blazor pages and components because I don't want to reference the Application layer from Web.Shared project. Is that the right approach? or should I define Permissions enum in another place?

This is the right approach for an application that has a single Blazor front end. If you added a mobile app or something else, you might need to rename / re-organise the Web.Shared project so that it can be used by the other apps. It could be named ProjectName.Common or something else that more accurately describes the purpose of the project.
