### ISSUE TITLE
[Question] CleanArchitecture vs NorthwindTraders

### ISSUE THREAD

**Issue by davidhenley** [jasontaylordev/CleanArchitecture#32]
Hey Jason, I just wanted to know what the differences are in these 2 projects.

- What is this project trying to accomplish that NorthwindTraders doesn't?
- Are you happy with both projects architectures?
- Is there anything you would change about NWT?
- What are your plans for the future?

**Comment by MCCshreyas** [comment]
This is the template of clean architecture and NWT is built upon this template! 
OR 
Moreover, Jason created this CA template for those who want some clean architecture boilerplate.

**Comment by jasontaylordev** [comment]
Hi @davidhenley - thanks for the questions and sorry for the late reply. I've limited capacity right now, recently had twins and sleep is hard to come by. 😐

I built Northwind Traders first, just as a sample project in .NET Core / EF Core so I had something to try things out. The template was built as a result of everything learned from Northwind Traders. I want to focus most of my effort on the template now since I have limited capacity.

> What is this project trying to accomplish that NorthwindTraders doesn't?

This project is a template for .NET Core. I can now run `dotnet new ca-sln` and start coding. It just provides the best File > New Project experience.

> Are you happy with both projects architectures?

Yes, they should be closely aligned. I think Northwind needs some updates.

> Is there anything you would change about NWT?

It's not actually generated from the template - since it came first. I'd love for it to be completely aligned to the template. So it is essentially a sample of what you can build using the template. I'd also like to upgrade the schema - Northwind 2020. 😁

> What are your plans for the future?

This year I am going to focus on enhancing the template based on feedback and experience. I'm publishing a series of blog posts on Clean Architecture with .NET - the first one is already done - https://jasontaylor.dev/clean-architecture-getting-started. I'm also running a number of Clean Architecture workshops in Australia and potentially online (as per blog post).
