### ISSUE TITLE
Notifications in the entities => bad idea

### ISSUE THREAD

**Issue by alvipeo** [jasontaylordev/CleanArchitecture#345]
Why is notifications are part of Domain Entities? Even though with it's inside entity props setters.
This looks wrong to me. Notifications belong to Request/Handler mechanism. What if I have more complex logic in the Command? This would force me to change Entities...

This is wrong IMO.

**Comment by alvipeo** [comment]
What about sharing some thoughts on this instead of liking/disliking it? We're not on FB shit here.

**Comment by superdac** [comment]
From the implementation, it's pretty obvious why the `DomainEvents` are tied to the domain entities... It allows for the events to be emitted when the changes are saved. Check the `DispatchEvents` method:
https://github.com/jasontaylordev/CleanArchitecture/blob/d0f133ee026aec5cd5856c5592c307b5f20fa8e4/src/Infrastructure/Persistence/ApplicationDbContext.cs#L70
You can probably decide what to do with these events in the event handlers instead of changing entities.
On the other hand, if you find yourself in the need for a mechanism to trigger events based on something else (not necessarily a property value change), you might want to look into [MediatR notifications](https://github.com/jbogard/MediatR/wiki#notifications). This might have the flexibility you're looking for.

**Comment by alvipeo** [comment]
if this repo is a template for Clean Architecture then nothing should be tied. Especially, aspects to the entities.

**Comment by kolpav** [comment]
@alvipeo This might be of interest to you https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation#the-deferred-approach-to-raise-and-dispatch-events

> What if I have more complex logic in the Command? This would force me to change Entities

I don't see how complexity of a command affect entities. You are free to implement however complex handling of dispatched notifications. You can even create domain events in response to domain events that is the reason for `while(true)` loop inside db context.
