### ISSUE TITLE
Feature Request: React Presentation Layer

### ISSUE THREAD

**Issue by chandrakanth553** [jasontaylordev/CleanArchitecture#35]
Add feature to select options for UI Application.

**Comment by jasontaylordev** [comment]
Hi @chandrakanth553 - this would be an awesome feature! I would love to support Angular, React, and Vue. Sadly, I am not sure I have the capacity to make this happen. I'll add it to the roadmap anyway - fingers crossed.

**Comment by yehudamakarov** [comment]
I'd be interested to help with a React UI layer. 
I'm thinking to start an application now using this template and I will use a React layer.

**Comment by mrrenaud** [comment]
Hi @jasontaylordev, I could propose a React layer, but how would you suggest to arrange the projects ? 

Should we add a new "WebUI" project with just the React config instead of Angular, and have a structure like this : 
```
src\
   |- Application
   |- Domain
   |- Infrastructure
   |- WebUI.Angular
   |- WebUI.React
```

Maybe this would be more difficult to maintain, as most of the code in WebUI projects would be duplicated.

But this would probably be messy to have both Angular and React client app in the same WebUI project. It requires different config for nswag, different config in the startup class.

What do you think? If you have any guidance I would be glad to help.
