### ISSUE TITLE
[Question] How to redirect all front-end requests?

### ISSUE THREAD

**Issue by adamshakhabov** [jasontaylordev/CleanArchitecture#357]
For development, I'd like to run back-end in Visual Studio in Debug mode and develop front-end separately in Visual Studio Code. As you know, by default, the back-end is up on localhost:5000 (dotnet run), front-end on localhost:4200 (npm start). **How I can redirect _all_ front-end requests to localhost:5000 while my development experience?**

I made some changes:

![image](https://user-images.githubusercontent.com/5969304/116811411-d178fd00-ab51-11eb-86c6-af9faaded729.png)

But it still uses localhost:4200:

![image](https://user-images.githubusercontent.com/5969304/116811504-6bd94080-ab52-11eb-80fc-c681aeb3f602.png)

Looks like some additional changes should be done or am I on the wrong way?

**Comment by kingjordan** [comment]
I also develop the back end in visual studio and the font end angular in vsCode.

How I do it:
set up a debug profile in vs code like this:
```
    {
      "name": "Launch Edge: 4200",
      "request": "launch",
      "type": "pwa-msedge",
      "url": "http://localhost:4200",
      "webRoot": "${workspaceFolder}/src/WebUI/ClientApp"
    },
```
run this debug profile and your front end should load.
I do this first so that when I debug the back end it can find localhost:4200 running for the proxy server

then in visual studio i set my build to **debug**, project to **webui** and then choose the name of your project from the debug profile list as seen bellow:
![Screenshot 2021-05-08 081709](https://user-images.githubusercontent.com/5931768/117542448-f0561400-afd5-11eb-9379-140a2dddf036.jpg)
now when I hit F5 or debug the angular app is already being served and breakpoints will be hit in both sides  You can adjust this so that they are only hit on front or back depending on what you need.

**Comment by adamshakhabov** [comment]
Thanks for the answer!

_Sorry, the question may be obvious, I am new in VS Code debugger._

I do the following:
1) Create launch.json:
```JSON
{
  "version": "0.2.0",
  "configurations": [
      {
          "type": "chrome",
          "request": "launch",
          "name": "Launch Chrome against localhost",
          "url": "http://localhost:4200",
          "webRoot": "${workspaceFolder}"
      }
  ]
}
```
2) `ng serve`
3) Run debug in VS Code -> a new Chrome's window is opening. And now front-end breakpoints are work!
4) Run back-end on the Visual Studio side -> app is running on localhost:5001. And now front-end changes are automatically detected and localhost:5001 is refreshed — Hot Reload works for localhost:5000/5001!
5) But API requests of Chrome's debug page (step 3) cannot get back-end:
![image](https://user-images.githubusercontent.com/5969304/117565079-2e2b6900-b0b8-11eb-90f1-ad3a4bcc4045.png)

**Comment by kingjordan** [comment]
if you dont want to hit backend breakpoints you can run the back end with the command 'dotnet run' from a terminal in the src/webapi directory of your project.  otherwise open the back end in visual studio and debug the project as I describe above, this works for me and its tough for me to debug your project because I cant see your project.  Good luck
