### ISSUE TITLE
[Question] / Enhancement: Provide samples for overriding identity pages

### ISSUE THREAD

**Issue by TheSchmu** [jasontaylordev/CleanArchitecture#38]
Hi Jason,

first of all: great template, thanks for all the hard work put into this repository! 

Following the clean architecture approach, can you either describe or provide a sample implementation of overriding the default identity pages? It would be trivial to scaffold any given identity page, such as login, logout, pw reset, etc. via Visual Studio. But this would generate MVC based razor pages and I wonder if there was an approach using the Angular 8 frontend within your clean architecture eco system that you'd recommend. 

Thank you very much in advance!

**Comment by MojtabaBarekati** [comment]
Hi TheSchmu and 
  Hi Jason and thanks
i had this situation too!
i think it is not possible to do that  because of theory of single sign on (the app uses identity server).
let assume that we done that(turn razor pages to angular components) => what will happen when identity should redirect to other pages?!

i do not know that this idea is OK or not!!!

**Comment by Pyrobolser** [comment]
@TheSchmu that's a great question, thank you for asking it I am really looking forward to the answer as it would make sense to have everything on the Angular side.  
I tried to do it by myself but didn't succeed yet and for now I am using the MVC pages for this purpose, but I would love to get rid of them. Have you been able to find any examples or documentation to help you achieve this goal yet?

**Comment by Semicolon192** [comment]
Man I would love to know this too, It gets overridden a little bit with the _LoginPartial.cshtml but I cant figure out how it actually targets the IdentityServer Login page its soo weird! I don't see the views at all and Identity Server docs have no actual examples with using the built in views.

Also the Pages navbar don't match the original IdentityServer nav I don't see any reference to this being changed but behold it is.

**Comment by Semicolon192** [comment]
Okay I figured out How! Its so hard to get Information about this. Sorry I'm trying to run out the door now but........

started from here
[Scaffold-Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=netcore-cli)

Didn't fully read it but it seems Microsoft has the pages precompiled if you dont include them


So just to generate the login and registerpages I ran this
```
dotnet tool install -g dotnet-aspnet-codegenerator
dotnet aspnet-codegenerator identity  --files "Account.Register;Account.Login"
```

**Make sure to do a local git commit so you can see everything this changed!!**

It created a few dbcontexts data folders, you can safely delete this. 

You will want to update 
`UserManager<IdentityUser> UserManager` => `UserManager<ApplicationUser> UserManager`
`SignInManager<IdentityUser> SignInManager` => `SignInManager<ApplicationUser> SignInManager`

on cshtml.cs files (along with the matching injection placeholder ie "_usermanager")

and then the register user page you need to change
line ~78  `var user = new IdentityUser ` to  `var user = new ApplicationUser `

**Comment by Pyrobolser** [comment]
@Semicolon192 That part I was ok with.
You can also right-click the Web project and in the Add menu select New Scaffolded Item.  
So this add all of the actual views in the project and you can override from here but I was looking for an actual clean Angular solution to replace all of this but maybe there is no other solution than "Just do it yourself" for the moment.

**Comment by jasontaylordev** [comment]
This is not something I have done yet. I would love to rewrite all as Angular components but not sure if I can take a partial approach. It seems like a lot of work. I would essentially scaffold, as per above, rewrite as Angular components, and rely on JavaScript services and client-side routing to do the rest. This is all in theory. I haven't tried as yet.

Thoughts?

**Comment by Pyrobolser** [comment]
In my opinion, I do not think any of this is actually _on you_. As of today, the ASP.NET Core Angular template is still _in between_ two worlds because of the authentication part. It makes stuff kinda weird for the CSS, etc.
  
If you want the authentication part, there is no easy way to opt out what you don't need, you have to add them explicitly and redirect the user to your home page. For example, I had to do that from the register pages as people are not supposed to be able to register in my application by themselves.

So I was thinking of doing the authentication part, etc in Angular too so all the views are in Angular only. I'm not really a big front-end developer with Angular and I was thinking of looking into [this guide](https://fullstackmark.com/post/21/user-authentication-and-identity-with-angular-aspnet-core-and-identityserver) but I haven't had time yet.

**Comment by TheSchmu** [comment]
I agree with @Pyrobolser , this shouldn't be on you :-) 

If I find the spare time, I would love to prepare a sample on how to approach my mid-December thoughts. I'm thinking of implementing maybe two or three views and providing a guideline for others to approach the "rest".
I actually kinda like the project structure of the aspnetboilerplate team, in which they created a separate ngmodule containing pretty much everything related to identity views. 

However, someone pitched the idea to feature additional presentation layers to your template, (personally, I would prefer a react ui, as well :-) ). I think time's spent more wisely to analyse and approach that with higher priority :)

Cheers from Germany

**Comment by jasontaylordev** [comment]
Thanks all for the discussion and feedback.
