### ISSUE TITLE
anyone know why webui integration test icon different then others?

### ISSUE THREAD

**Issue by teamsmiley** [jasontaylordev/CleanArchitecture#41]
![image](https://user-images.githubusercontent.com/4934139/71284334-5a094b80-2317-11ea-8f59-96d86cd75268.png)

what type of this project

**Comment by jasontaylordev** [comment]
Hey @teamsmiley. I think it is because in ASP .NET Core 3, it was necessary to specify the Web SDK in the project file (<Project Sdk="Microsoft.NET.Sdk.Web">); https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.0#test-app-prerequisites.

As of 3.1, this is no longer the case:

![image](https://user-images.githubusercontent.com/1988321/74145582-f16d8980-4c4a-11ea-9714-95d5ad76ea93.png)
