### ISSUE TITLE
getting error "No connection could be made because the target machine actively refused it."

### ISSUE THREAD

**Issue by avishekroychowdhury** [jasontaylordev/CleanArchitecture#431]
**Describe the bug**
I have set up the application as per the steps outlined in [https://github.com/jasontaylordev/CleanArchitecture](url).
Now while trying to access https://localhost:5001/, getting the socket exception : "No connection could be made because the target machine actively refused it."

**To Reproduce**
1. Set up the application as per the steps outlined in [https://github.com/jasontaylordev/CleanArchitecture](url).
2. After step 8, when I am trying to access https://localhost:5001/, getting the socket exception : "No connection could be made because the target machine actively refused it."
3. Have installed cert for iis.
4. Have not configured Docker for Windows, not sure if that's mandatory or not.

**Expected behavior**
The Project UI should display 

**Screenshots**
![SocketException](https://user-images.githubusercontent.com/7944380/130007602-62025a6a-6d83-4b21-84e7-117afa1c76f0.PNG)

**Additional context**

**Comment by SSRazvan** [comment]
use npm run start, to start the client

**Comment by ZeeshanAK** [comment]
I had the same problem. The issue was the ClientApp was not running. Execute the following commands and then try again.

1. Navigate to src/WebUI/ClientApp and run `npm install`
2. Navigate to src/WebUI/ClientApp and run `npm start `to launch the front end (Angular)

**Comment by jasontaylordev** [comment]
It's covered here - https://github.com/jasontaylordev/CleanArchitecture#getting-started

**Comment by markfilan** [comment]
This error is a network-related error occurred while establishing a connection to the Server. It means that the error is occurring because there is no server listening at the hostname and port you assigned. It literally means that the machine exists but that it has no services listening on the specified port . So, no connection can be established. Generally, it happens that something is preventing a connection to the port or hostname. Either there is a firewall blocking the connection or the process that is hosting the service is not listening on that specific port. This may be because it is not running at all or because it is listening on a different port. So, [no connection](http://csharp.net-informations.com/communications/connection.htm) can be established.

Try running netstat -anb from the command line to see if there's anything listening on the port you were entered. If you get nothing, try changing your port number and see if that works for you.  In Windows operating systems, you can use the netstat services via the command line (cmd.exe) . On Linux you may need to do netstat -anp instead.

The target machine actively refused it occasionally , it is likely because the server has a full 'backlog' . Regardless of whether you can increase the server backlog , you do need retry logic in your client code, sometimes it cope with this issue; as even with a long backlog the server might be receiving lots of other requests on that port at that time.
