### ISSUE TITLE
Long running tasks (Quartz.NET)

### ISSUE THREAD

**Issue by achmstein** [jasontaylordev/CleanArchitecture#48]
Hello,

I would like to use Quartz.NET. Where should I define my jobs? And how to schedule jobs?

Thanks

**Comment by jasontaylordev** [comment]
Hi @achmstein. I haven't used Quartz.NET - but treat it the same as you would other infrastructure. Within application, create an interface and associated types. For example:

```csharp
public interface IJobScheduler
{
    void Schedule(Job job, Trigger trigger)
}
```

In the above example, the interface and associated types (`Job` and `Trigger`) are not related to Quartz.NET. In fact, the application layer has no reference to the Quartz.NET package. 

Within Infrastructure. add a reference to the Quartz.NET package and implement the `IJobScheduler` interface.

I am sure your IJobScheduler will need additional methods, just try to keep it simple. You're not trying to provide an interface that can access every feature of Quartz.NET, in fact, you should forget that you are using Quartz.NET - because, in the future, you may not be. So your interface and types within the Application layer should all be in support of job scheduling, containing only the functionality you need right now.

I hope this helps, happy coding.

**Comment by achmstein** [comment]
I really appreciate your help. Thank you.
