### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by EhsanHabib** [jasontaylordev/CleanArchitecture#532]
### Discussed in https://github.com/jasontaylordev/CleanArchitecture/discussions/531

<div type='discussions-op-text'>

<sup>Originally posted by **EhsanHabib** December 21, 2021</sup>
I have added a new controller in the controllers folder but it is not appearing in the swagger api.</div>

**Comment by AliGhIO** [comment]
> ### Discussed in #531
> Originally posted by **EhsanHabib** December 21, 2021 I have added a new controller in the controllers folder but it is not appearing in the swagger api.

Does your controller have [ApiController] attribute? I think only api controllers are displayed in swagger.

**Comment by demchenkov** [comment]
This can happen if you run your application in Release mode without having previously run it in Debug mode. Simply because NSwag generates new documentation only after building in **Debug** mode. You can check your specification file (`src/WebUI/wwwroot/api/specification.json`). If this file contains the new routes, clear your browser cache. It may help

**Comment by jasontaylordev** [comment]
Thanks. Assuming this is resolved, feel free to comment if not.
