### ISSUE TITLE
Why is Infrastructure project is targetting dotnet core 3.1 ?

### ISSUE THREAD

**Issue by utkarsh24** [jasontaylordev/CleanArchitecture#565]
Hi, 
I am using this template using dotnet core 3.1 

I observed that Infrastructue project is targeting to .net core 3.1 while Application and Domain projects targeting to dotnetstandard 2.1

https://github.com/jasontaylordev/CleanArchitecture/blob/netcore3.1/src/Application/Application.csproj

Could you please let me know the reason for this?

**Comment by nibro7778** [comment]
Right now infrastructure project is targeting [.net 6.0](https://github.com/jasontaylordev/CleanArchitecture/blob/35b490110f699c2ba427fd6b49e98babc16390c0/src/Infrastructure/Infrastructure.csproj?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L4) mostly because of EntityFramework

Application & Domain projects are simple class library as it doesn't require any host. Your UI/Presentation layer needs .net 6 as its required web host.

**Comment by jernejk** [comment]
You're looking at .NET Core 3.1 branch and long story short, .NET Standard 2.1 allows you to use the library in .NET Core and .NET Framework, making it more portable.

EF Core 3.1 didn't initially support .NET Standard and was recommended to be used on .NET Core 3.1 onwards.

Since .NET 5, .NET Standard is no longer useful, unless you need Xamarin or .NET Framework support.
