### ISSUE TITLE
[Question] How do I set an applicationUser to an entity as child object ?

### ISSUE THREAD

**Issue by TANIAX** [jasontaylordev/CleanArchitecture#58]
Hello,

I'm new to .net core and just began to clean arch, but I got some trouble to getting started 

Can you help me? 

`
public class TodoList
    {
        public int Id { get; set; }

        public virtual ApplicationUser AssignTO { get; set; }
   }

`

I can't do this because Applicationuser comes from Infrastructure, and my object entity comes from the domain 

I have a circular dependency ....

**Comment by jasontaylordev** [comment]
Hi @TANIAX. Ideally, you should keep Identity concerns such as **ApplicationUser** separate from your **Domain**. If you would like a list owner, as per your above example, this could be implemented as follows:

```csharp
    public class TodoList : AuditableEntity
    {
        public TodoList()
        {
            Items = new List<TodoItem>();
        }

        public int Id { get; set; }

        public string IdentityUserId { get; set; } // The Id of Application User from Identity

        public string Title { get; set; }

        public IList<TodoItem> Items { get; set; }
    }
```

In this way, you know who owns the list, without need to reference `ApplicationUser` directly.

If you need to do more, you might consider creating a separate **User** entity within your **Domain**, again with the **IdentityUserId** linking the entity back to Identity.

If you feel this approach is too complex and would like a simpler solution, then add ApplicationUser to your Domain. This is not ideal if you're trying to support complex business logic with a DDD approach, but most certainly provides a much easier way to get up and running.

**Comment by TANIAX** [comment]
Hi @jasontaylordev, thanks a lot for your anwser !

The second approach is the best solution for me, just tested it and it 100% working for my needs.

**Comment by HybridSolutions** [comment]
> Hi @TANIAX. Ideally, you should keep Identity concerns such as **ApplicationUser** separate from your **Domain**. If you would like a list owner, as per your above example, this could be implemented as follows:
> 
> ```cs
>     public class TodoList : AuditableEntity
>     {
>         public TodoList()
>         {
>             Items = new List<TodoItem>();
>         }
> 
>         public int Id { get; set; }
> 
>         public string IdentityUserId { get; set; } // The Id of Application User from Identity
> 
>         public string Title { get; set; }
> 
>         public IList<TodoItem> Items { get; set; }
>     }
> ```
> 
> In this way, you know who owns the list, without need to reference `ApplicationUser` directly.
> 
> If you need to do more, you might consider creating a separate **User** entity within your **Domain**, again with the **IdentityUserId** linking the entity back to Identity.
> 
> If you feel this approach is too complex and would like a simpler solution, then add ApplicationUser to your Domain. This is not ideal if you're trying to support complex business logic with a DDD approach, but most certainly provides a much easier way to get up and running.

I've been reading about Clean Architecture and found that all examples and projects stop exactly at this point. If you don't want to extend ApplicationUser with custom properties how to relate AspnetUsers table content with other tables without moving ApplicationUser to the Domain layer. The answer presented here is interesting but creates a couple of issues:

1. Guarantee that when creating, updating or deleting a new user, the dependent tables get also updated. This will force to make multiple DB calls and use transactions to make sure we don't end up with orphan data.
2. In a modular project, that dependes on AspNetUsers, how do you ensure that the module data is inserted, updated or deleted upon changes on an IdentityUser from outside the module scope? How do you enforce this kind of rules in the development of modular functionalities? The ApplicationUser is not aware of these "virtual" connections between tables or even the modules that reference users id. 

I'm a fan of this architecture, but would be interesting to see one complete example dealing and solving these issues because they are on of the most asked questions in all of the Clean Architecture projects I've seen. 

Please do not take this as a criticism of this particular project, but as a general limitation on the intentions to present an interesting architecture to new or experienced programmers.
