### ISSUE TITLE
Use xUnit

### ISSUE THREAD

**Issue by nbbdev** [jasontaylordev/CleanArchitecture#610]
**Is your feature request related to a problem? Please describe.**
I used this source and at first the tests were very slow and tedious because nunit was used.

**Describe the solution you'd like**
I used xunit and everything got super fast and better and I was also much faster in running parallel tests

**Describe alternatives you've considered**
use XUnit

what is your opinion?

**Comment by Bardin08** [comment]
I also prefer to use `xUnit` for unit tests because of its parallel running tests support. And what's more afaik today almost everywhere xUnit is preferable.

@nbbdev, you mentioned that you used xUnit. Was that an attempt to update this template? If yes, I think it would be perfect if you would create a PR.

**Comment by jasontaylordev** [comment]
I covered this in my talk - https://youtu.be/2UJ7mAtFuio

**Comment by bramburn** [comment]
It seems fine

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Hasan Arab Borzo ***@***.***>
Sent: Monday, April 18, 2022 1:05:20 PM
To: jasontaylordev/CleanArchitecture ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jasontaylordev/CleanArchitecture] Use xUnit (Issue #610)


Is your feature request related to a problem? Please describe.
I used this source and at first the tests were very slow and tedious because nunit was used.

Describe the solution you'd like
I used xunit and everything got super fast and better and I was also much faster in running parallel tests

Describe alternatives you've considered
use XUnit

what is your opinion?
