### ISSUE TITLE
code for Nuget  Clean.Architecture have issue with nswag.msbuild

### ISSUE THREAD

**Issue by mrs01dev** [jasontaylordev/CleanArchitecture#613]
**Describe the bug**
Nuget  for Clean.Architecture  need to be updated.

this is repeated issue for :

[https://github.com/jasontaylordev/CleanArchitecture/issues/504](url)

The following error is result from using  Clean.Architecture  Nuget package :
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "dotnet .....
.nuget\packages\nswag.msbuild\13.9.4\build\../tools/Net50/dotnet-nswag.dll" run nswag.json /variables:Configuration=Debug" exited with code -2147450730.	WebUI	..\jasontaylordev\src\WebUI\WebUI.csproj	59	

**Steps to reproduce the behavior**:
Run dotnet new --install Clean.Architecture.Solution.Template to install the project template
Create a folder for your solution and cd into it (the template will use it as project name)
Run dotnet new ca-sln to create a new project
Navigate to src/WebUI/ClientApp and run npm install
Navigate to src/WebUI/ClientApp and run npm start to launch the front end (Angular)
Navigate to src/WebUI and run dotnet run to launch the back end (ASP.NET Core Web API).'

**Additional context**
Downloaded code from GitHub does not have this  issue.

**Comment by TRiBotWillB** [comment]
Is this a fix for this yet?

**Comment by sxyxs** [comment]
I have got same error

**Comment by sandygeeks** [comment]
I faced the same issue and this worked for me.
I installed .Net 5.0.0 

1. SDK 5.0.100 and 
2. ASP.NET Core Runtime 5.0.0

You can find them here.
[https://dotnet.microsoft.com/en-us/download/dotnet/5.0](https://dotnet.microsoft.com/en-us/download/dotnet/5.0)

Also updated the two NSwag.AspNetCore and NSwag.MSBuild to latest stable version from Nuget Package Manager.
However, I don't think this is necessary.

I think it is because in WebUI.csproj we have **NSwagExe_Net50**
`        <Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net50) run nswag.json /variables:Configuration=$(Configuration)" />
`
which requires .Net5 sdks and all.

**Comment by jasontaylordev** [comment]
Sorry about this, I've released a new version to NuGet that will resolve this issue.

**Comment by sandygeeks** [comment]
No worries.
Thank you for the hard work you do.

**Comment by jasontaylordev** [comment]
You're welcome, happy coding! 😀
