### ISSUE TITLE
Extend ApplicationUser with Domain entities relationship

### ISSUE THREAD

**Issue by Pyrobolser** [jasontaylordev/CleanArchitecture#71]
Hello,

I was wondering how one could extend the `ApplicationUser` the cleanest way possible if I need a one-to-many relationship between `ApplicationUser` and one entity from my Domain project.
Should I just move `ApplicationUser` to my Domain model? Right now, I cannot do it since my domain model has no idea about `ApplicationUser`.

**Comment by khaledafify** [comment]
try this solution
https://github.com/jasontaylordev/CleanArchitecture/issues/58#issuecomment-584055887

**Comment by Pyrobolser** [comment]
I will check it out, thank you!

**Comment by Pyrobolser** [comment]
So, in my case, I need the "more complex solution" since I need an `ApplicationUser` to have a specific `EntityId` and my `Entity` has a `ICollection<ApplicationUser>` so I should have an extra `User` table within my Domain with an `IdentityUserId` if I understand correctly?
I don't think this is going to actually help me since at one point I am going to need to had all those tables/foreign keys to my migration files and I am going to link the `ApplicationUser` from a class inside the `Domain` project...
Sadly I think I don't have a choice but to move the `ApplicationUser` to Domain.

**Comment by GFoley83** [comment]
The comment khaledafify linked to solves your problem I feel:

> If you need to do more, you might consider creating a separate User entity within your Domain, again with the IdentityUserId linking the entity back to Identity.

`User` has an `EntityId` and a `IdentityUserId`. `Entity` has an `ICollection<User>` for example. No need for `ApplicationUser` to be added to the Domain class.

**Comment by Pyrobolser** [comment]
When adding the `Configuration` for the new User model with EF model builder, how do I tell the model builder that there is a one-to-one relationship between `User` and `ApplicationUser`?
I think I'm not getting this solution, where in the application should I use `ApplicationUser`, where should I use `User` then?  
Sorry if it's obvious, it's just getting more confusing like this to me.

**Comment by GFoley83** [comment]
> When adding the Configuration for the new User model with EF model builder, how do I tell the model builder that there is a one-to-one relationship between User and ApplicationUser?

You don't because `ApplicationUser` isn't part of your domain. `ApplicationUser` is only meant to be used for identity management i.e. storing info about the users of your system. 

If all you're trying to do is associate who owns a particular custom entity, have it inherit from `AuditableEntity` just like `TodoItem` and `TodoList` do. If you look in the `SaveChangesAsync` inside `ApplicationDbContext.cs` you'll see that when an item is added to the database, the current user id is added also.

I think the main problem here is that you have clearly explained what it is you're trying to accomplish. You mentioned you want a one-to-many relationship with `ApplicationUser` but not why you want that.

**Comment by Pyrobolser** [comment]
I want the current user connected to the application to be able to access one specific `Entity`.
So I just added an `EntityId` in my `AspNetUsers` table.  
This `Entity` is already in the database and is not created nor updated by the `ApplicationUser` itself. This user just owns it and can access it.

**Comment by GFoley83** [comment]
Then you already have multiple options listed above to accomplish that. 

The easiest and quickest way is to simply have `Entity` inherit from `AuditableEntity`. This way the `CreatedBy` property will be populated with the current user's ID automatically when `Entity` is added to the Db.

When retrieving `Entity` from the Db, just inject `ICurrentUserService` into your Get Entity handler and select where  `CreatedBy == _currentUserService.UserId`.

E.e.
```cs
public class GetEntityQueryHandler : IRequestHandler<GetEntityQuery, EntityDto>
{
    private readonly IApplicationDbContext _context;
    private readonly IMapper _mapper;
    private readonly ICurrentUserService _currentUserService;

    public GetEntityQueryHandler(IApplicationDbContext context,
        ICurrentUserService currentUserService)
    {
        _context = context;
        _currentUserService = currentUserService;
    }

    public async Task<EntityDto> Handle(GetEntityQuery request, CancellationToken cancellationToken)
    {
        var entity = _context.Entity
            .FirstOrDefaultAsync(i => i.CreatedBy == _currentUserService.UserId);

        return _mapper.Map<Entity, EntityDto>(entity);
    }
}
```

In any case, your issue is a software design issue and not an issue related to this project. 
The above comments more than cover the issue you described. If you need further help, I suggest you post a question on StackOverflow (where questions like this belong).

Good luck.

**Comment by jasontaylordev** [comment]
Thanks for your help @GFoley83. 😀
