### ISSUE TITLE
webapi installed, Webui Bug

### ISSUE THREAD

**Issue by xoose** [jasontaylordev/CleanArchitecture#927]
**To Reproduce**
1. Project created with Visual Studio - newest version VS & newest version CleanArchitecture
2. WebApi created with sqlite (no react or angular) only API
3. WebApi started
4. NU1104 = src\WebUI\WebUI.csproj not found 
= NU1104	Das Projekt "repos\xxxx\xxxx\src\WebUI\WebUI.csproj" not found. 

project not found Application.IntegrationTests	
\repos\xxxx\xxxx\tests\Application.IntegrationTests	\repos\xxxx\xxxx\tests\Application.IntegrationTests\Application.IntegrationTests.csproj	1	

In Application.Integration.Tests  

ItemGroup>
      ProjectReference Include="..\..\src\WebUI\WebUI.csproj" 
ItemGroup

change to =
ItemGroup
     ProjectReference Include="..\..\src\WebApi\WebApi.csproj"
ItemGroup

**Second Error:**

config.nswag 
     "aspNetCoreToOpenApi": {
      **"project": "WebUI.csproj",**
 change to 
**"project": "WebApi.csproj",**

**Comment by jasontaylordev** [comment]
Thanks @xoose for reporting this issue, much appreciated!

Rather than continue using `WebUI` and `WebApi` project names, I've opted to just use `Web` project name for both SPA and Web API projects. This has simplified the template and will resolve your issue.

Please install the [latest template](https://www.nuget.org/packages/Clean.Architecture.Solution.Template/8.0.0-preview.6.1) and try again:

```bash
dotnet new update Clean.Architecture.Solution.Template::8.0.0-preview.6.1
```

Let me know if you run into any other issues. 😀
