### ISSUE TITLE
✨ Include Docker Support

### ISSUE THREAD

**Issue by ManuelNinyo** [jasontaylordev/CleanArchitecture#929]
###  It could be useful.To add support for docker.

And please consider:

1. ready for production
2. integration test docker compose

**Comment by jasontaylordev** [comment]
Agreed, it could be useful. Docker was included in the past, but I removed since I didn't have time to fix it after it broke. If you're interested in adding support raise a PR and ensure that Docker support works for both SPA variants (Angular + React) and Web API only. This will require some conditional logic for building the template, if you need help with that - let me know.

> And please consider:
> 1. ready for production
> 2. integration test docker compose

What are you asking for. are these separate features?

**Comment by jasontaylordev** [comment]
Thanks for raising this issue. Since I haven't received any follow-up responses, I'll close it.
Feel free to open a new one if needed.
