### ISSUE TITLE
React for dotNet7?

### ISSUE THREAD

**Issue by ashleysommer** [jasontaylordev/CleanArchitecture#991]
I just started using CleanArchitecture for a new project this week.
It is a dotNet7 project, but we want to use React for the ClientApp.
The README in `main` mentions ability to use React, but after installing CleanArchitecture 7.0.2 it is clear that React client support was introduced _after_ the fork to dotNet8-preview.

I managed to get a solution working by studying #872 and applying the same changes to my built App. 
Adding this required tweaking some parts here and there to get it working on the older codebase (eg, Controllers instead of Endpoints, adjusting to the older style React template, etc).

Do you think it is worth doing a proper backport of the React support into the CleanArchitecture `net7` branch for those who need it?

**Comment by jasontaylordev** [comment]
Hi @ashleysommer. Thanks for reaching out, I don't think it is worthwhile for two reasons:

1. .NET 8 is almost production-ready and will be the long-term support version (supported until Nov 2026). Support for .NET 7 ends in May 2024. I only have the capacity to focus on the current SDK.

2. This template uses the original Angular and React templates. Unfortunately, as of .NET 8 Preview 7, this approach has been dropped; https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-7/#new-visual-studio-templates.

I'll have to work out a new approach for Angular and React since I don't have the capacity to support that either. 🤣

**Comment by ashleysommer** [comment]
Thanks for the reply @jasontaylordev 
I didn't notice that Preview 7 introduce that new style of React and Angular template, that is definitely going to be a headache for you.
